packaging_format = 2

id = "garage"
name = "Garage"
description.en = "S3 storage"
description.fr = "stockage S3"

version = "0.9.2~ynh1"

maintainers = ["oiseauroch"]

[upstream]
license = "AGPL-3.0-only"
website = "https://garagehq.deuxfleurs.fr/"
admindoc = "https://garagehq.deuxfleurs.fr/documentation/quick-start/"
userdoc = "https://garagehq.deuxfleurs.fr/documentation/quick-start/"
code = "https://git.deuxfleurs.fr/Deuxfleurs/garage"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.rpc_secret]
    ask.en = "UUID of the network (rpc-secret) "
    ask.fr = "UUID de l'ilot (rpc-secret)"
    type = "string"
    optional = true
    example = "1799bccfd7411eddcf9ebd316bc1f5287ad12a68094e1c6ac6abde7e6feae1ec"

    [install.bootstrap_peers]
    ask.en = "friend server id"
    ask.fr = "serveur ami"
    type = "string"
    example = "1799bccfd7411eddcf9ebd316bc1f5287ad12a68094e1c6ac6abde7e6feae1ec@127.0.0.1:3901"
    optional = true

    [install.weight]
    ask.en = "Number of GB to allow for storage"
    ask.fr = "Nombre de GB à allouer pour le stockage"
    type = "number"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    extract = false
    amd64.url = "https://garagehq.deuxfleurs.fr/_releases/v0.9.2/x86_64-unknown-linux-musl/garage"
    amd64.sha256 = "5e9ddd7bf397d07cbf9c36630c6871688adbcbf31873127f99c63320459483fc"
    arm64.url = "https://garagehq.deuxfleurs.fr/_releases/v0.9.2/aarch64-unknown-linux-musl/garage"
    arm64.sha256 = "a7fabef132f2f71607df6b2343860c3e0d80ad7fee2e7150d703958a49e37191"
    i386.url = "https://garagehq.deuxfleurs.fr/_releases/v0.9.2/i686-unknown-linux-musl/garage"
    i386.sha256 = "4cea631fb3d110725ed349e435dde911f7a9efe810ccbc670043ea3bb52c5fe4"
    armhf.url = "https://garagehq.deuxfleurs.fr/_releases/v0.9.2/armv6l-unknown-linux-musleabihf/garage"
    armhf.sha256 = "8fc03edb615e78462a1bd58ccbd083e319b8b8d3f80fe430f2b599d5e4791485"

    [resources.ports]
    main.default = 4000
    main.exposed = "TCP"
    api.default = 5000
    web.default = 6000

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["data", "metadata"]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages_from_raw_bash = """
    systemd-detect-virt -q -c && echo "qemu-utils e2fsprogs" || true
    """
