packaging_format = 2

id = "garage"
name = "Garage"
description.en = "S3 storage"
description.fr = "stockage S3"

version = "0.9.4~ynh1"

maintainers = [ "oiseauroch" ]

[upstream]
license = "AGPL-3.0-only"
website = "https://garagehq.deuxfleurs.fr/"
admindoc = "https://garagehq.deuxfleurs.fr/documentation/quick-start/"
userdoc = "https://garagehq.deuxfleurs.fr/documentation/quick-start/"
code = "https://git.deuxfleurs.fr/Deuxfleurs/garage"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.rpc_secret]
    ask.en = "UUID of the network (rpc-secret) "
    ask.fr = "UUID de l'ilot (rpc-secret)"
    type = "string"
    optional = true
    example = "1799bccfd7411eddcf9ebd316bc1f5287ad12a68094e1c6ac6abde7e6feae1ec"

    [install.bootstrap_peers]
    ask.en = "friend server id"
    ask.fr = "serveur ami"
    type = "string"
    example = "1799bccfd7411eddcf9ebd316bc1f5287ad12a68094e1c6ac6abde7e6feae1ec@127.0.0.1:3901"
    optional = true

    [install.weight]
    ask.en = "Number of GB to allow for storage"
    ask.fr = "Nombre de GB à allouer pour le stockage"
    type = "number"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    extract = false
    amd64.url = "https://garagehq.deuxfleurs.fr/_releases/v0.9.4/x86_64-unknown-linux-musl/garage"
    amd64.sha256 = "965712193116fddccb85b8e58a192be723e8f2fc7c4a3123704c6d7bdc3d050f"
    arm64.url = "https://garagehq.deuxfleurs.fr/_releases/v0.9.4/aarch64-unknown-linux-musl/garage"
    arm64.sha256 = "2e5cc060742969d0b607728525fa535f07a2b133ac2c96057241fb467a7fb45a"
    i386.url = "https://garagehq.deuxfleurs.fr/_releases/v0.9.4/i686-unknown-linux-musl/garage"
    i386.sha256 = "4cdc26178284a1f92d8aba38c240d8d4cf775837da2ac7bb8fb4c603a546dff5"
    armhf.url = "https://garagehq.deuxfleurs.fr/_releases/v0.9.4/armv6l-unknown-linux-musleabihf/garage"
    armhf.sha256 = "e0dfc6391e6f75c4ddaf6e3b7e36e2fe19555bcd332fd283f643bfc46613dbe9"

    [resources.ports]
    main.default = 4000
    main.exposed = "TCP"
    api.default = 5000
    web.default = 6000

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["data", "metadata"]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages_from_raw_bash = """
    systemd-detect-virt -q -c && echo "qemu-utils e2fsprogs" || true
    """
