packaging_format = 2

id = "garage"
name = "Garage"
description.en = "S3 storage"
description.fr = "stockage S3"

version = "1.0.0~ynh1"

maintainers = [ "oiseauroch" ]

[upstream]
license = "AGPL-3.0-only"
website = "https://garagehq.deuxfleurs.fr/"
admindoc = "https://garagehq.deuxfleurs.fr/documentation/quick-start/"
userdoc = "https://garagehq.deuxfleurs.fr/documentation/quick-start/"
code = "https://git.deuxfleurs.fr/Deuxfleurs/garage"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.rpc_secret]
    ask.en = "UUID of the network (rpc-secret) "
    ask.fr = "UUID de l'ilot (rpc-secret)"
    type = "string"
    optional = true
    example = "1799bccfd7411eddcf9ebd316bc1f5287ad12a68094e1c6ac6abde7e6feae1ec"

    [install.bootstrap_peers]
    ask.en = "friend server id"
    ask.fr = "serveur ami"
    type = "string"
    example = "1799bccfd7411eddcf9ebd316bc1f5287ad12a68094e1c6ac6abde7e6feae1ec@127.0.0.1:3901"
    optional = true

    [install.weight]
    ask.en = "Number of GB to allow for storage"
    ask.fr = "Nombre de GB à allouer pour le stockage"
    type = "number"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    extract = false
    amd64.url = "https://garagehq.deuxfleurs.fr/_releases/v1.0.0/x86_64-unknown-linux-musl/garage"
    amd64.sha256 = "2bd72c49961c84139175b4fb47bdd349e324006d78854b90e8d1040e0d07927b"
    arm64.url = "https://garagehq.deuxfleurs.fr/_releases/v1.0.0/aarch64-unknown-linux-musl/garage"
    arm64.sha256 = "64dce2913ca65aafa90ea7aa9f1d7ac3b65f7ba5e642ff3d744ca710f2cd6f87"
    i386.url = "https://garagehq.deuxfleurs.fr/_releases/v1.0.0/i686-unknown-linux-musl/garagee"
    i386.sha256 = "d10eeabf06a8884e0f06a25a3e0995642a27e8a3597f5c129c001748fa33ad92"
    armhf.url = "https://garagehq.deuxfleurs.fr/_releases/v1.0.0/armv6l-unknown-linux-musleabihf/garage"
    armhf.sha256 = "ad3dd17b594d5ed5f21105c3c30f9e7e4a0ab825ed758df6a0d0fd27237a02e7"

    [resources.ports]
    main.default = 4000
    main.exposed = "TCP"
    api.default = 5000
    web.default = 6000

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["data", "metadata"]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages_from_raw_bash = """
    systemd-detect-virt -q -c && echo "qemu-utils e2fsprogs" || true
    """
