packaging_format = 2

id = "garage"
name = "Garage"
description.en = "S3 storage"
description.fr = "stockage S3"

version = "0.9.1~ynh1"

maintainers = ["oiseauroch"]

[upstream]
license = "AGPL-3.0-only"
website = "https://garagehq.deuxfleurs.fr/"
admindoc = "https://garagehq.deuxfleurs.fr/documentation/quick-start/"
userdoc = "https://garagehq.deuxfleurs.fr/documentation/quick-start/"
code = "https://git.deuxfleurs.fr/Deuxfleurs/garage"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.rpc_secret]
    ask.en = "UUID of the network (rpc-secret) "
    ask.fr = "UUID de l'ilot (rpc-secret)"
    type = "string"
    optional = true
    example = "1799bccfd7411eddcf9ebd316bc1f5287ad12a68094e1c6ac6abde7e6feae1ec"

    [install.bootstrap_peers]
    ask.en = "friend server id"
    ask.fr = "serveur ami"
    type = "string"
    example = "1799bccfd7411eddcf9ebd316bc1f5287ad12a68094e1c6ac6abde7e6feae1ec@127.0.0.1:3901"
    optional = true

    [install.weight]
    ask.en = "Number of GB to allow for storage"
    ask.fr = "Nombre de GB à allouer pour le stockage"
    type = "number"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    extract = false
    amd64.url = "https://garagehq.deuxfleurs.fr/_releases/v0.9.1/x86_64-unknown-linux-musl/garage"
    amd64.sha256 = "7932b8073aaba4521f8fd30a8e4c9dfb1b948a3d9d120d456aa883c5a2d73f50"
    arm64.url = "https://garagehq.deuxfleurs.fr/_releases/v0.9.1/aarch64-unknown-linux-musl/garage"
    arm64.sha256 = "b79d83d0332de55d27110aaad9dccfdf464e20f63b748c10d1a49a3d162401c3"
    i386.url = "https://garagehq.deuxfleurs.fr/_releases/v0.9.1/i686-unknown-linux-musl/garage"
    i386.sha256 = "45da5319be845528a3965cdf883c6d052b57ff296ae3d72027c5c3fe8cf5251a"
    armhf.url = "https://garagehq.deuxfleurs.fr/_releases/v0.9.1/armv6l-unknown-linux-musleabihf/garage"
    armhf.sha256 = "d5a898d7f0eb967d2594ac3a51b60ef3d1acf29fa108d2a61c56b1b810721359"

    [resources.ports]
    main.default = 4000
    main.exposed = "TCP"
    api.default = 5000
    web.default = 6000

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["data", "metadata"]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages_from_raw_bash = """
    systemd-detect-virt -q -c && echo "qemu-utils e2fsprogs" || true
    """
