test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = ["install.private", "install.root", "install.subdir", "install.multi"]

    # -------------------------------
    # Default args to use for install
    # -------------------------------
        args.weight = "10"
